### ISSUE TITLE
How do you bind event handlers?

### ISSUE THREAD

**Issue by dfischer** [Meteor-Community-Packages/meteor-autocomplete#102]
How would you bind event handlers to the text area? 

I.e 

```
 {{> inputAutocomplete settings=settings id="msg" class="input-xlarge" placeholder="Chat..." data-action="doSomething"}}
```

```
Template.foo.events({
  'keyup data-action=doSomething': function() {
    alert('hi');
  }
});
```

Seems like this isn't possible? Not sure how you'd do anything with a textarea on submitting anything unless this was possible?

**Comment by mizzao** [comment]
That should work as you have it, except for the syntax problem: `'keyup input[data-action="doSomething"]'`

Also check out the `autocompleteselect` event descrbed in the docs.
