### ISSUE TITLE
Value for field

### ISSUE THREAD

**Issue by mrn3** [Meteor-Community-Packages/meteor-autocomplete#70]
I have autocomplete working well, but I can't get it to insert the value of the field.  In other words, I have the autocomplete field on a form that populates values from the database, and I want the autocomplete field to have the value from the database.

I know this is bad syntax because I am putting handlebars within handlebars, but I am not sure how to do this:

{{> inputAutocomplete settings=settings id="openingHymn" name="openingHymn" value="{{openingHymn}}" class="form-control" placeholder="Opening Hymn"}}

Do I need to get inside your package and put the value inside your template?  I am not sure how to accomplish this without getting inside your template.

Thanks.

**Comment by shrop** [comment]
@mrn3 thanks for your example `selector` function. It helped me figure some things out on my autocomplete functionality!

**Comment by mrn3** [comment]
You bet - no problem!

**Comment by ketankulkarni** [comment]
thanx
can you post your code
