### ISSUE TITLE
Use with Autoform Package

### ISSUE THREAD

**Issue by sandman18** [Meteor-Community-Packages/meteor-autocomplete#9]
Is it possible to use this with the autoform package?  If so can you give an example of how you would use the two together?

Thanks

**Comment by pajooh** [comment]
Hi @mizzao, as autoform is going to widely be used in meteor land, i think it's very good to have some kind of integration between autocomplete and autoform, e.g. creating a [form widget](https://github.com/aldeed/meteor-autoform#defining-custom-input-types) for autocomplete

**Comment by mizzao** [comment]
Currently on vacation and would be happy to take a look at this when I get back. In the meantime, do you have any suggestions for how to do it?

**Comment by nikhildaga** [comment]
@mizzao : there is already a package for it : https://atmospherejs.com/mpowaga/autoform-autocomplete , https://github.com/mpowaga/meteor-autoform-autocomplete/
