### ISSUE TITLE
Html attribute "autocomplete" is not set when input is renderend

### ISSUE THREAD

**Issue by joarobles** [Meteor-Community-Packages/meteor-autocomplete#99]
This is an example of the generated html for the autocomplete input,

```
<input type="text" id="q" class="form-control" placeholder="Search...">
```

It should contain the html attribute autocomplete="off" in order to prevent the browser from filling the input resulting in two selection windows.

**Comment by mizzao** [comment]
Thanks for the report, will update this soon.

**Comment by aessig** [comment]
Any news about that ?

**Comment by joarobles** [comment]
perfect timing
